/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.ui;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
public class Home extends javax.swing.JFrame {

    int count= 3;
    DBConnect con = new DBConnect();
    Connection conny;
    public Home() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        navigationContainer = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        dashButton = new javax.swing.JButton();
        shopButton = new javax.swing.JButton();
        locationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        pictureContainer = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        testimonialContainer = new javax.swing.JPanel();
        feedback = new javax.swing.JTextField();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationContainer.setBackground(new java.awt.Color(38, 64, 84));

        homeButton.setBackground(new java.awt.Color(38, 64, 84));
        homeButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        dashButton.setBackground(new java.awt.Color(38, 64, 84));
        dashButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        dashButton.setText("Dashboard");
        dashButton.setBorder(null);
        dashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashButtonActionPerformed(evt);
            }
        });

        shopButton.setBackground(new java.awt.Color(38, 64, 84));
        shopButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        shopButton.setText("Shop");
        shopButton.setBorder(null);
        shopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopButtonActionPerformed(evt);
            }
        });

        locationButton.setBackground(new java.awt.Color(38, 64, 84));
        locationButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        locationButton.setText("Locations");
        locationButton.setBorder(null);
        locationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(38, 64, 84));
        logoutButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationContainerLayout = new javax.swing.GroupLayout(navigationContainer);
        navigationContainer.setLayout(navigationContainerLayout);
        navigationContainerLayout.setHorizontalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashButton, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(shopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(locationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigationContainerLayout.setVerticalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationContainerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        bg.add(navigationContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 560));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logo.setDisabledIcon(null);
        logo.setMaximumSize(new java.awt.Dimension(0, 0));
        logo.setMinimumSize(new java.awt.Dimension(0, 0));
        logo.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pictureContainerLayout = new javax.swing.GroupLayout(pictureContainer);
        pictureContainer.setLayout(pictureContainerLayout);
        pictureContainerLayout.setHorizontalGroup(
            pictureContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pictureContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        pictureContainerLayout.setVerticalGroup(
            pictureContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(pictureContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        scrollbar1.setBackground(new java.awt.Color(255, 255, 255));
        scrollbar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollbar1.setForeground(new java.awt.Color(249, 62, 0));
        scrollbar1.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        bg.add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 502, 650, -1));

        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testimonialContainerLayout = new javax.swing.GroupLayout(testimonialContainer);
        testimonialContainer.setLayout(testimonialContainerLayout);
        testimonialContainerLayout.setHorizontalGroup(
            testimonialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testimonialContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previous)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next)
                .addGap(14, 14, 14))
        );
        testimonialContainerLayout.setVerticalGroup(
            testimonialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testimonialContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(testimonialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous)
                    .addComponent(feedback, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(next))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(testimonialContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 399, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void dashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Dashboard().setVisible(true);
        
    }//GEN-LAST:event_dashButtonActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        // TODO add your handling code here:
        
        try{
            
            con.DBConnect();
            //conny = DriverManager.getConnection("jdbc:mysql://localhost/pataspare","root","");
            PreparedStatement feed = con.getConny().prepareStatement("SELECT * FROM `feedback` WHERE `feedbackId`=?");
            feed.setInt(1, 3);
            ResultSet r = feed.executeQuery();
            if(r.next()){
                feedback.setText(r.getString("review"));
            }
        
    }catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_feedbackActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/hlogo.jpg"));
        logo.setIcon(icon);
        count++;
        try{
            con.DBConnect();
            PreparedStatement feed = con.getConny().prepareStatement("SELECT * FROM `feedback` WHERE `feedbackId`=?");
            feed.setInt(1, count);
            ResultSet r = feed.executeQuery();
            if(r.next()){
                feedback.setText(r.getString("review"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
        count--;
        try{
            PreparedStatement feed = con.getConny().prepareStatement("SELECT * FROM `feedback` WHERE `feedbackId`=?");
            feed.setInt(1, count);
            ResultSet r = feed.executeQuery();
            if(r.next()){
                feedback.setText(r.getString("review"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_previousActionPerformed

    private void shopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Shop().setVisible(true);
    }//GEN-LAST:event_shopButtonActionPerformed

    private void locationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Locations().setVisible(true);
    }//GEN-LAST:event_locationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeelbgetClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } bgInstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton dashButton;
    private javax.swing.JTextField feedback;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton locationButton;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navigationContainer;
    private javax.swing.JButton next;
    private javax.swing.JPanel pictureContainer;
    private javax.swing.JButton previous;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JButton shopButton;
    private javax.swing.JPanel testimonialContainer;
    // End of variables declaration//GEN-END:variables
}
