/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.ui;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author otien
 */
public class Locations extends javax.swing.JFrame {

    /**
     * Creates new form Locations
     */
    public Locations() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        navigationContainer = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        dashButton = new javax.swing.JButton();
        shopButton = new javax.swing.JButton();
        locationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        contactusButton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        pic2 = new javax.swing.JLabel();
        tyrex = new javax.swing.JButton();
        auto = new javax.swing.JButton();
        cng = new javax.swing.JButton();
        cmc = new javax.swing.JButton();
        kenyaTyres = new javax.swing.JButton();
        kingsway = new javax.swing.JButton();
        national = new javax.swing.JButton();
        tyremasters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationContainer.setBackground(new java.awt.Color(38, 64, 84));

        homeButton.setBackground(new java.awt.Color(38, 64, 84));
        homeButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        dashButton.setBackground(new java.awt.Color(38, 64, 84));
        dashButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        dashButton.setText("Dashboard");
        dashButton.setBorder(null);
        dashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashButtonActionPerformed(evt);
            }
        });

        shopButton.setBackground(new java.awt.Color(38, 64, 84));
        shopButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        shopButton.setText("Shop");
        shopButton.setBorder(null);
        shopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopButtonActionPerformed(evt);
            }
        });

        locationButton.setBackground(new java.awt.Color(38, 64, 84));
        locationButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        locationButton.setText("Locations");
        locationButton.setBorder(null);
        locationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(38, 64, 84));
        logoutButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        contactusButton.setBackground(new java.awt.Color(38, 64, 84));
        contactusButton.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        contactusButton.setText("Contact Us");
        contactusButton.setBorder(null);
        contactusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationContainerLayout = new javax.swing.GroupLayout(navigationContainer);
        navigationContainer.setLayout(navigationContainerLayout);
        navigationContainerLayout.setHorizontalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(shopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(locationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contactusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigationContainerLayout.setVerticalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationContainerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        bg.add(navigationContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bg.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        tyrex.setBackground(new java.awt.Color(255, 255, 255));
        tyrex.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tyrex.setForeground(new java.awt.Color(249, 62, 0));
        tyrex.setText("Tyrex Kenya");
        tyrex.setBorder(null);
        tyrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyrexActionPerformed(evt);
            }
        });
        bg.add(tyrex, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 390, 190, 30));

        auto.setBackground(new java.awt.Color(255, 255, 255));
        auto.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        auto.setForeground(new java.awt.Color(249, 62, 0));
        auto.setText("AutoXpress");
        auto.setBorder(null);
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });
        bg.add(auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 426, 190, 30));

        cng.setBackground(new java.awt.Color(255, 255, 255));
        cng.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        cng.setForeground(new java.awt.Color(249, 62, 0));
        cng.setText("Car and General");
        cng.setBorder(null);
        cng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngActionPerformed(evt);
            }
        });
        bg.add(cng, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 462, 190, 30));

        cmc.setBackground(new java.awt.Color(255, 255, 255));
        cmc.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        cmc.setForeground(new java.awt.Color(249, 62, 0));
        cmc.setText("CMC Motors");
        cmc.setBorder(null);
        cmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmcActionPerformed(evt);
            }
        });
        bg.add(cmc, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 498, 190, 30));

        kenyaTyres.setBackground(new java.awt.Color(255, 255, 255));
        kenyaTyres.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        kenyaTyres.setForeground(new java.awt.Color(249, 62, 0));
        kenyaTyres.setText("Kenya Tyres");
        kenyaTyres.setBorder(null);
        kenyaTyres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kenyaTyresActionPerformed(evt);
            }
        });
        bg.add(kenyaTyres, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 190, 30));

        kingsway.setBackground(new java.awt.Color(255, 255, 255));
        kingsway.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        kingsway.setForeground(new java.awt.Color(249, 62, 0));
        kingsway.setText("Kingsway Tyres");
        kingsway.setBorder(null);
        kingsway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kingswayActionPerformed(evt);
            }
        });
        bg.add(kingsway, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 426, 190, 30));

        national.setBackground(new java.awt.Color(255, 255, 255));
        national.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        national.setForeground(new java.awt.Color(249, 62, 0));
        national.setText("National Oil");
        national.setBorder(null);
        national.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalActionPerformed(evt);
            }
        });
        bg.add(national, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 462, 190, 30));

        tyremasters.setBackground(new java.awt.Color(255, 255, 255));
        tyremasters.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tyremasters.setForeground(new java.awt.Color(249, 62, 0));
        tyremasters.setText("Tyremasters");
        tyremasters.setBorder(null);
        tyremasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyremastersActionPerformed(evt);
            }
        });
        bg.add(tyremasters, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 498, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ContactUs().setVisible(true);
    }//GEN-LAST:event_contactusButtonActionPerformed

    private void tyrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyrexActionPerformed
        // TODO add your handling code here:
        
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/tyrex.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_tyrexActionPerformed

    private void tyremastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyremastersActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/tyremasters.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_tyremastersActionPerformed

    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/autoxpress.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_autoActionPerformed

    private void cngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/carNgeneral.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_cngActionPerformed

    private void cmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmcActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/cmc.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_cmcActionPerformed

    private void kenyaTyresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kenyaTyresActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/kenyaTyres.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_kenyaTyresActionPerformed

    private void kingswayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kingswayActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/kingsway.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_kingswayActionPerformed

    private void nationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalActionPerformed
        // TODO add your handling code here:
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/project/ui/images/nationalOil.jpg"));
        pic2.setIcon(icon);
    }//GEN-LAST:event_nationalActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void dashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_dashButtonActionPerformed

    private void shopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Shop().setVisible(true);
    }//GEN-LAST:event_shopButtonActionPerformed

    private void locationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Locations().setVisible(true);
    }//GEN-LAST:event_locationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Locations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auto;
    private javax.swing.JPanel bg;
    private javax.swing.JButton cmc;
    private javax.swing.JButton cng;
    private javax.swing.JButton contactusButton;
    private javax.swing.JButton dashButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton kenyaTyres;
    private javax.swing.JButton kingsway;
    private javax.swing.JButton locationButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton national;
    private javax.swing.JPanel navigationContainer;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel pic2;
    private javax.swing.JButton shopButton;
    private javax.swing.JButton tyremasters;
    private javax.swing.JButton tyrex;
    // End of variables declaration//GEN-END:variables
}
